### ISSUE TITLE
Class does not exist

### ISSUE THREAD

**Issue by decadence** [codestudeo/laravel-totem#17]
I created task via Totem and was trying to run it and I got:
![screenshot_1](https://user-images.githubusercontent.com/1434668/29744188-88ccaaa2-8aa8-11e7-9a4c-447f1efdfce8.png)

**Comment by roshangautam** [comment]
This issue has been fixed in refactor/notifications branch. I will tag another alpha release as soon as am done working on a few more enhancements.

**Comment by roshangautam** [comment]
A new alpha [release](https://github.com/codestudeo/laravel-totem/releases/tag/v0.4.0) has been tagged. Please upgrade accordingly to get this issue resolved.

**Comment by decadence** [comment]
@roshangautam now I have update issue
![screenshot_2](https://user-images.githubusercontent.com/1434668/29748562-c5276194-8b21-11e7-9423-c26ed728ec57.png)

**Comment by roshangautam** [comment]
Sorry about that, just tagged another alpha with a less firm dependencies such as the package can be installed in L5.4 and above. Please try updating and see what happens.
