### ISSUE TITLE
"EXECUTE" button's link is 404

### ISSUE THREAD

**Issue by royalwang** [codestudeo/laravel-totem#22]
我的本地测试地址是http://localhost/laravel-blog/public/totem/tasks/4 ，程序运行在子目录下。但是点击“执行”按钮所请求的地址是http://localhost/totem/tasks/4/execute 。其他位置的链接点击都正常，就这个“执行”按钮点击时404。

**Comment by roshangautam** [comment]
Thanks for reporting. This is definitely an issue when Laravel is installed in a subdirectory.

**Comment by roshangautam** [comment]
Please update to latest alpha. Dont forget to run `php artisan totem:assets`.
